apiVersion: v1
kind: ConfigMap
metadata:
  name: dongtai-iast-config.ini
  namespace: {{ .Release.Namespace }}
data:
  config.ini: |-
    {{ include "config.ini" . }}
  {{- if (.Files.Glob "config/**") }}
  {{ range $path, $bytes := .Files.Glob "config/**" }}
  {{- $path | replace "config/" "" | b64enc | replace "=" "-" | indent 2 }}: |
  {{ $.Files.Get $path | b64enc | indent 4 }}
  {{ end }}
  {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-cm
  namespace: {{ .Release.Namespace }}
data:
  database: {{.Values.mysql.host}}:{{.Values.mysql.port}}/{{.Values.mysql.name}}
  username: {{.Values.mysql.user}}
  password: {{.Values.mysql.password}}
---
apiVersion: v1
data:
  nginx.conf: |-
    {{ include "nginx.conf" . }}
kind: ConfigMap
metadata:
  name: dongtai-web-nginx-conf
  namespace: {{.Release.Namespace}}
---