{{- if .Values.max }}
---
apiVersion: v1
kind: Service
metadata:
  name: dongtai-doc-svc
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ template "dongtai.fullname" . }}-doc
  type: ClusterIP
{{- end }}