---
apiVersion: v1
kind: Service
metadata:
  name: dongtai-server-svc
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ template "dongtai.fullname" . }}-server
  type: ClusterIP