---
#dongtai-logstash服务
apiVersion: v1
kind: Service
metadata:
  name: dongtai-logstash-svc
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
  - name: http-agent
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: tcp-log
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: {{ template "dongtai.fullname" . }}-logstash