---
#dongtai-worker-task服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-task
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-task
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-task
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-task
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      annotations:
        server_number: {{.Values.build.server_number}}
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-task
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
  {{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-task-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/bash","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "beat" ]
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}