# Generated by Django 3.2.20 on 2023-07-28 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0002_auto_20230726_1433"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IastRole",
            new_name="IastRoleV2",
        ),
        migrations.AddField(
            model_name="iastproject",
            name="projectgroups",
            field=models.ManyToManyField(
                through="dongtai_common.IastProjectGroupProject", to="dongtai_common.IastProjectGroup"
            ),
        ),
        migrations.AddField(
            model_name="iastproject",
            name="users",
            field=models.ManyToManyField(
                related_name="auth_projects", through="dongtai_common.IastProjectUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="iastprojectgroup",
            name="projects",
            field=models.ManyToManyField(
                through="dongtai_common.IastProjectGroupProject", to="dongtai_common.IastProject"
            ),
        ),
        migrations.AddField(
            model_name="iastprojectgroup",
            name="users",
            field=models.ManyToManyField(through="dongtai_common.IastProjectGroupUser", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="iastprojectgroup",
            name="create_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="create_project_group",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
