# Generated by Django 3.2.20 on 2023-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0006_auto_20230803_1407"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="iastprojectgroupproject",
            constraint=models.UniqueConstraint(
                fields=("project_id", "project_group_id"), name="iast_project_group_project_unique_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="iastprojectgroupuser",
            constraint=models.UniqueConstraint(
                fields=("user_id", "project_group_id"), name="iast_project_group_user_unique_constraint"
            ),
        ),
    ]
