# Generated by Django 3.2.20 on 2023-08-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0008_alter_iastprojectmetadata_project"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="iastprojectgroupproject",
            index=models.Index(fields=["project_group_id", "project_id"], name="iast_projec_project_931f04_idx"),
        ),
        migrations.AddIndex(
            model_name="iastprojectgroupuser",
            index=models.Index(fields=["project_group_id", "user_id"], name="iast_projec_project_7637b6_idx"),
        ),
        migrations.AddIndex(
            model_name="iastprojectuser",
            index=models.Index(fields=["user_id", "project_id"], name="iast_projec_user_id_94ba48_idx"),
        ),
        migrations.AddIndex(
            model_name="iastrolev2",
            index=models.Index(fields=["status"], name="iast_role_status_b13c48_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["deleted"], name="auth_user_deleted_30f14e_idx"),
        ),
        migrations.AddConstraint(
            model_name="iastprojectuser",
            constraint=models.UniqueConstraint(
                fields=("project_id", "user_id"), name="iast_project_user_unique_constraint"
            ),
        ),
    ]
