# Generated by Django 3.2.20 on 2023-08-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongtai_common', '0009_auto_20230808_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iastprojectgroup',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='iastrolev2',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
