# Generated by Django 3.2.20 on 2023-08-14 15:37

from django.db import migrations


def update_role_permission(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("dongtai_common", "User")
    for user in User.objects.all():
        if user.pk == 1:
            user.role_id = 1
            user.is_global_permission = True
        else:
            user.role_id = 2
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0010_auto_20230809_1838"),
    ]

    operations = [
        migrations.RunPython(update_role_permission),
    ]
