# Generated by Django 3.2.20 on 2023-08-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0013_auto_20230822_1202"),
    ]

    operations = [
        migrations.CreateModel(
            name="VulMethodPool",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("method_pool_id", models.IntegerField(default=0)),
                ("url", models.CharField(blank=True, max_length=2000)),
                ("uri", models.CharField(blank=True, max_length=2000)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("http_scheme", models.CharField(blank=True, max_length=20)),
                ("http_protocol", models.CharField(blank=True, max_length=255)),
                ("req_header", models.CharField(blank=True, max_length=2000, null=True)),
                ("req_params", models.CharField(blank=True, max_length=2000, null=True)),
                ("req_data", models.CharField(blank=True, max_length=4000, null=True)),
                ("res_header", models.CharField(blank=True, max_length=1000, null=True)),
                ("res_body", models.TextField(blank=True, null=True)),
                ("req_header_fs", models.TextField(db_column="req_header_for_search")),
                ("context_path", models.CharField(blank=True, max_length=255, null=True)),
                ("method_pool", models.TextField()),
                ("pool_sign", models.CharField(blank=True, max_length=40, unique=True)),
                ("clent_ip", models.CharField(blank=True, max_length=255)),
                ("create_time", models.IntegerField()),
                ("update_time", models.IntegerField()),
                ("uri_sha1", models.CharField(blank=True, db_index=True, max_length=40)),
                (
                    "agent",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dongtai_common.iastagent",
                    ),
                ),
                (
                    "vul",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dongtai_common.iastvulnerabilitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "iast_agent_method_pool_vul",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="vulmethodpool",
            index=models.Index(fields=["uri_sha1", "http_method", "agent"], name="iast_agent__uri_sha_c94d8d_idx"),
        ),
        migrations.AddIndex(
            model_name="vulmethodpool",
            index=models.Index(fields=["method_pool_id"], name="iast_agent__method__46f7b0_idx"),
        ),
        migrations.AddIndex(
            model_name="vulmethodpool",
            index=models.Index(fields=["vul_id", "update_time"], name="iast_agent__vul_id_47b430_idx"),
        ),
    ]
