# Generated by Django 3.2.20 on 2023-08-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0014_auto_20230825_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulmethodpool",
            name="method_pool_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vulmethodpool",
            name="vul",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="dongtai_common.iastvulnerabilitymodel",
            ),
        ),
        migrations.AddIndex(
            model_name="vulmethodpool",
            index=models.Index(fields=["method_pool_id"], name="iast_agent__method__46f7b0_idx"),
        ),
        migrations.AddIndex(
            model_name="vulmethodpool",
            index=models.Index(fields=["vul_id"], name="iast_agent__vul_id_6f1c90_idx"),
        ),
        migrations.AddIndex(
            model_name="vulmethodpool",
            index=models.Index(fields=["update_time"], name="iast_agent__update__718d63_idx"),
        ),
    ]
