# Generated by Django 3.2.20 on 2023-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0016_auto_20230829_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vulmethodpool",
            name="pool_sign",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
