# Generated by Django 3.2.20 on 2023-08-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0017_alter_vulmethodpool_pool_sign"),
    ]

    operations = [
        migrations.CreateModel(
            name="IastPackageFocus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("language_id", models.IntegerField()),
                ("package_name", models.CharField(max_length=255)),
                ("package_version", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "iast_package_focus",
            },
        ),
        migrations.AddField(
            model_name="assetv2global",
            name="is_focus",
            field=models.BooleanField(default=False),
        ),
    ]
