# Generated by Django 3.2.20 on 2023-08-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0018_auto_20230830_1105"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assetv2global",
            index=models.Index(
                fields=["is_focus", "vul_count", "aql", "level", "language_id"], name="iast_asset__is_focu_31e975_idx"
            ),
        ),
    ]
