# Generated by Django 3.2.20 on 2023-09-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0019_assetv2global_iast_asset__is_focu_31e975_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="IastAgentRequestChainsTopoGraph",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("graph_hash", models.CharField(blank=True, max_length=255, unique=True)),
                ("dot_string", models.TextField()),
                ("max_depth", models.IntegerField()),
                (
                    "start_project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dongtai_common.iastproject",
                    ),
                ),
                (
                    "start_project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
            ],
            options={
                "db_table": "iast_request_chains_topo_graph",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IastAgentRequestChainsTopoGraphVec",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level_id", models.IntegerField()),
                ("source_node_tag", models.CharField(blank=True, max_length=255)),
                ("target_node_tag", models.CharField(blank=True, max_length=255)),
                (
                    "graph_hash",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dongtai_common.iastagentrequestchainstopograph",
                        to_field="graph_hash",
                    ),
                ),
                (
                    "source_project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="source_project",
                        to="dongtai_common.iastproject",
                    ),
                ),
                (
                    "source_project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="source_project_version",
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="target_project",
                        to="dongtai_common.iastproject",
                    ),
                ),
                (
                    "target_project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="target_project_version",
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
            ],
            options={
                "db_table": "iast_request_chains_topo_graph_vecs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IastAgentRequestChainsTotalProjectVersionGraphVec",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="total_source_project_version",
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
                (
                    "target_project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="total_target_project_version",
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
            ],
            options={
                "db_table": "iast_request_chains_total_project_version_graph_vec",
                "managed": True,
                "unique_together": {("source_project_version", "target_project_version")},
            },
        ),
        migrations.CreateModel(
            name="IastAgentRequestChainsTotalProjectGraphVec",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="total_source_project",
                        to="dongtai_common.iastproject",
                    ),
                ),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="total_target_project",
                        to="dongtai_common.iastproject",
                    ),
                ),
            ],
            options={
                "db_table": "iast_request_chains_total_project_graph_vec",
                "managed": True,
                "unique_together": {("source_project", "target_project")},
            },
        ),
    ]
