# Generated by Django 3.2.20 on 2023-09-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dongtai_common",
            "0020_iastagentrequestchainstopograph_iastagentrequestchainstopographvec_iastagentrequestchainstotalprojec",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IastWebHookLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=255)),
                ("body", models.JSONField()),
                ("create_time", models.IntegerField()),
            ],
            options={
                "db_table": "iast_webhook_log",
                "managed": True,
            },
        ),
    ]
