# Generated by Django 3.2.20 on 2023-09-11 14:16

import shortuuid.django_fields
from django.db import migrations
from shortuuid import ShortUUID


def update_exist_project_token(apps, schema_editor):
    IastProject = apps.get_model("dongtai_common", "IastProject")
    objs_list = []
    for project in IastProject.objects.all():
        project.token = ShortUUID(alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789").random(
            length=22
        )
        objs_list.append(project)
    IastProject.objects.bulk_update(objs_list, ["token"])


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0021_iastwebhooklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="iastproject",
            name="token",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                length=22,
                max_length=22,
                prefix="",
            ),
        ),
        migrations.RunPython(update_exist_project_token),
    ]
