# Generated by Django 3.2.20 on 2023-09-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0023_auto_20230912_1211"),
    ]

    operations = [
        migrations.AddField(
            model_name="iastsensitiveinforule",
            name="system_type",
            field=models.IntegerField(default=0),
        ),
    ]
