# Generated by Django 3.2.20 on 2023-09-14 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0024_iastsensitiveinforule_system_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="iastagentrequestchainstopographvec",
            unique_together={("graph_hash", "source_node_tag", "target_node_tag")},
        ),
    ]
