# Generated by Django 3.2.20 on 2023-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0027_auto_20230919_1233"),
    ]

    operations = [
        migrations.AddField(
            model_name="hookstrategy",
            name="modified",
            field=models.BooleanField(default=False),
        ),
    ]
