# Generated by Django 3.2.20 on 2023-09-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0028_hookstrategy_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
