# Generated by Django 3.2.20 on 2023-09-26 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0029_user_totp_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="IastAgentRequestChainsTopoTotalProjectVersionGraph",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("graph_hash", models.CharField(blank=True, max_length=255, unique=True)),
                ("dot_string", models.TextField()),
            ],
            options={
                "db_table": "iast_request_chains_topo_total_project_version_graph",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IastAgentRequestChainsTopoTotalProjectVersionGraphVec",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="total_source_project_version_node",
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
                (
                    "target_project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="total_target_project_version_node",
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
                (
                    "total_project_version_graph",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dongtai_common.iastagentrequestchainstopograph",
                        to_field="graph_hash",
                    ),
                ),
            ],
            options={
                "db_table": "iast_request_chains_topo_total_project_version_graph_vec",
                "managed": True,
                "unique_together": {
                    ("total_project_version_graph", "source_project_version", "target_project_version")
                },
            },
        ),
        migrations.CreateModel(
            name="IastAgentRequestChainsTopoTotalProjectVersionGraphProjectRel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "project_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=-1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dongtai_common.iastprojectversion",
                    ),
                ),
                (
                    "total_project_version_graph",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dongtai_common.iastagentrequestchainstopototalprojectversiongraph",
                        to_field="graph_hash",
                    ),
                ),
            ],
            options={
                "db_table": "iast_request_chains_topo_total_project_version_graph_rel",
                "managed": True,
                "unique_together": {("total_project_version_graph", "project_version")},
            },
        ),
    ]
