# Generated by Django 3.2.20 on 2023-09-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dongtai_common",
            "0030_iastagentblackrule_iastagentblackruledetail_iastagentrequestchainstopototalprojectversiongraph_iasta",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="iastagentrequestchainstopototalprojectversiongraphvec",
            name="total_project_version_graph",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                max_length=255,
                on_delete=django.db.models.deletion.CASCADE,
                to="dongtai_common.iastagentrequestchainstopototalprojectversiongraph",
                to_field="graph_hash",
            ),
        ),
    ]
