# Generated by Django 3.2.20 on 2023-10-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0033_auto_20231007_1152"),
    ]

    operations = [
        migrations.RunSQL(
            """
UPDATE auth_user  SET phone = "" WHERE phone IS NULL;
ALTER TABLE `auth_user` MODIFY `phone` varchar(255) DEFAULT '' NOT  NULL;

            """
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
