# Generated by Django 3.2.20 on 2023-10-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0034_auto_20231007_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
